Captain_Console/Captain_Console/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Captain.urls')),
    path('consoles/', include('Consoles.urls')),
    path('games/', include('Games.urls')),
    path('accessories/', include('Accessories.urls')),
    path('<int:pk>/', include('Captain.urls')),
    path('search/', include('Search.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('ShoppingCart.urls')),
    path('checkout/', include('Checkout.urls')),
    path('allproducts/', include('AllProducts.urls')),


]

Captain_Console/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', LoginView.as_view(template_name='user/login.html'), name="login"),
    path('logout', LogoutView.as_view(next_page="/"), name="logout"),
    path('profile', views.profile, name='profile')
]

Captain_Console/Captain/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999, blank=True)
    price = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    manufacturer = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    image = models.CharField(max_length=999)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)

    def __str__(self):
        return self.image

Captain_Console/templates/searchResult/search_results.html
{% extends 'base.html' %}


{% block content %}

{% if products %}
    <div class="w-50 center-block">
        <div class="container text-center">
          <div class = "row">
              {% for product in products %}
                          <div class="col-md-3 col-lg-3 col-xl-3 m-2">
                              <a href="/{{ product.id }}">
                                  <img class="w-100"  src="{{ product.productimages_set.first.image }}" alt="img" />
                                  <h4 class="">{{ product.name }}</h4>
                                  <h5>$ {{ product.price }}</h5>
                              </a>
                          </div>
              {% endfor %}
                </div>
        </div>
    </div>

{% else %}

  <div class="container">
    <div class="row">
      <div class="card m-auto">
        <div class="card-body mt-2 mb-2">
          <h2 class="card-title">
            No results
          </h2>
          <p>There were no results matching your search: "{{query}}".</p>
        </div>
      </div>
    </div>
  </div>

{% endif %}


{% endblock %}